### ISSUE TITLE
Fail to allocate memory for fcn32s

### ISSUE THREAD

**Issue by LemonATsu** [rgbond/chasing-cats#3]
Hello, rgbond,
I am currently trying to reproduce your work on my Jetson TX 1 board,
and built up my caffe with cuDNN and cuda support.
However, I've encountered a memory issue when I trying to load the pre-trained voc-fcn32s model.

`
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.`
`[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 544614787`
`I1017 15:34:49.314759  9447 net.cpp:761] Ignoring source layer data`
`I1017 15:34:49.314927  9447 net.cpp:761] Ignoring source layer data_data_0_split`
`I1017 15:34:49.461199  9447 net.cpp:761] Ignoring source layer drop6`
`I1017 15:34:49.480286  9447 net.cpp:761] Ignoring source layer drop7`
`I1017 15:34:49.482586  9447 net.cpp:761] Ignoring source layer loss`
`F1017 15:35:17.519323  9447 syncedmem.hpp:25] Check failed: *ptr host allocation of size 561259008
failed`
`*** Check failure stack trace: ***`
`Aborted
`
Also, I have checked the memory usage during the process of loading model, and the TX1 is surely run out of memory.

So my question is : have you encountered this issue on your TX1 board? Or you didn't try that model directly on TX1 board?

Thanks in advanced!

**Comment by rgbond** [comment]
Hi,

Yes, I've been running it continually since June. I saw this problem when Caffe was not using CUDNN. Please check your CUDNN configuration in Caffe.

**Comment by LemonATsu** [comment]
Hi,

Thanks for your reply, 
I've tried to rebuild my Caffe with cuDNN, but the memory issue still persist : 
the process will get killed by OS during forwarding stage.

Do you have any idea about this issue?

Thanks again!

**Comment by rgbond** [comment]
I checked my Caffe config. The file includes these entries:

USE_CUDNN := 1
CUDA_DIR := /usr/local/cuda-7.0
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
        -gencode arch=compute_20,code=sm_21 \
        -gencode arch=compute_30,code=sm_30 \
        -gencode arch=compute_35,code=sm_35 \
        -gencode arch=compute_50,code=sm_50 \
        -gencode arch=compute_50,code=compute_50
BLAS := atlas
PYTHON_INCLUDE := /usr/include/python2.7 \
        /usr/lib/python2.7/dist-packages/numpy/core/include
PYTHON_LIB := /usr/lib
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib
BUILD_DIR := build
DISTRIBUTE_DIR := distribute

Here's the output of the top command:
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND  
 2645 rgb       20   0 2426020 910648 633616 S  29.7 23.1 532:21.17 tbatch_infer.py

**Comment by LemonATsu** [comment]
Sorry for my late response!

I'll try to modify my Caffe config and see what will happen, 
thanks for your help!
